version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=birthdays_dev
      - POSTGRES_PASSWORD=birthdays_dev
      - POSTGRES_DB=birthdays_dev
    tmpfs: "/var/lib/postgresql/data:rw,size=${DB_STORAGE_SIZE:-1024}M"
  memcached-0:
    image: memcached:1.6.18
    # command: memcached -vv
  memcached-1:
    image: memcached:1.6.18
    # command: memcached -vv
  memcached-2:
    image: memcached:1.6.18
    # command: memcached -vv
  nginx-cache:
    build:
      context: ./nginx-cache
    network_mode: "service:app"
  app:
    build:
      context: ./birthdays
    environment:
    - RUST_LOG=info
    - SERVER_ADDR=0.0.0.0:8080
    - PG.HOST=postgres
    - PG.USER=birthdays_dev
    - PG.PASSWORD=birthdays_dev
    - PG.DBNAME=birthdays_dev
    ports:
    - "8080:8080"
    - "8000:8000"
    depends_on:
      - postgres